# Generated by Django 2.2 on 2020-06-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantityofproduct', models.IntegerField(blank=True, null=True)),
                ('quantityAvailable', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('p', 'Pulses'), ('O', 'Oil'), ('F', 'Flour'), ('V', 'Vegetable')], max_length=2)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(null=True)),
            ],
        ),
    ]
